# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MainWindow.ui'
##
## Created by: Qt User Interface Compiler version 5.15.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(600, 400)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.chooseFile_btn = QPushButton(self.centralwidget)
        self.chooseFile_btn.setObjectName(u"chooseFile_btn")
        self.chooseFile_btn.setGeometry(QRect(380, 200, 100, 30))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 205, 131, 22))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(240, 5, 121, 31))
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(30, 245, 68, 22))
        self.freqData = QLineEdit(self.centralwidget)
        self.freqData.setObjectName(u"freqData")
        self.freqData.setGeometry(QRect(100, 240, 100, 30))
        self.filePathData = QLineEdit(self.centralwidget)
        self.filePathData.setObjectName(u"filePathData")
        self.filePathData.setGeometry(QRect(150, 200, 220, 30))
        self.setFreq_btn = QPushButton(self.centralwidget)
        self.setFreq_btn.setObjectName(u"setFreq_btn")
        self.setFreq_btn.setGeometry(QRect(210, 240, 80, 30))
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(40, 70, 80, 22))
        self.textBrowser = QTextBrowser(self.centralwidget)
        self.textBrowser.setObjectName(u"textBrowser")
        self.textBrowser.setGeometry(QRect(30, 40, 540, 150))
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(40, 100, 68, 22))
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(40, 130, 68, 22))
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(40, 160, 61, 22))
        self.filePath = QLabel(self.centralwidget)
        self.filePath.setObjectName(u"filePath")
        self.filePath.setGeometry(QRect(120, 70, 431, 22))
        self.fmFreq = QLabel(self.centralwidget)
        self.fmFreq.setObjectName(u"fmFreq")
        self.fmFreq.setGeometry(QRect(110, 100, 441, 22))
        self.psText = QLabel(self.centralwidget)
        self.psText.setObjectName(u"psText")
        self.psText.setGeometry(QRect(100, 130, 451, 22))
        self.rtText = QLabel(self.centralwidget)
        self.rtText.setObjectName(u"rtText")
        self.rtText.setGeometry(QRect(100, 160, 451, 22))
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(30, 285, 68, 22))
        self.psTextData = QLineEdit(self.centralwidget)
        self.psTextData.setObjectName(u"psTextData")
        self.psTextData.setGeometry(QRect(100, 280, 271, 32))
        self.setPsText_btn = QPushButton(self.centralwidget)
        self.setPsText_btn.setObjectName(u"setPsText_btn")
        self.setPsText_btn.setGeometry(QRect(380, 280, 100, 30))
        self.setRtText_btn = QPushButton(self.centralwidget)
        self.setRtText_btn.setObjectName(u"setRtText_btn")
        self.setRtText_btn.setGeometry(QRect(380, 320, 100, 30))
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(30, 325, 68, 22))
        self.rtTextData = QLineEdit(self.centralwidget)
        self.rtTextData.setObjectName(u"rtTextData")
        self.rtTextData.setGeometry(QRect(100, 320, 271, 32))
        self.start_btn = QPushButton(self.centralwidget)
        self.start_btn.setObjectName(u"start_btn")
        self.start_btn.setGeometry(QRect(250, 360, 99, 30))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.start_btn.setFont(font)
        self.version = QLabel(self.centralwidget)
        self.version.setObjectName(u"version")
        self.version.setGeometry(QRect(487, 380, 111, 22))
        self.version.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.chooseFile_btn.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.freqData.raise_()
        self.filePathData.raise_()
        self.setFreq_btn.raise_()
        self.textBrowser.raise_()
        self.label_5.raise_()
        self.label_4.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.filePath.raise_()
        self.fmFreq.raise_()
        self.psText.raise_()
        self.rtText.raise_()
        self.label_8.raise_()
        self.psTextData.raise_()
        self.setPsText_btn.raise_()
        self.setRtText_btn.raise_()
        self.label_9.raise_()
        self.rtTextData.raise_()
        self.start_btn.raise_()
        self.version.raise_()

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"PiFmRds GUI", None))
        self.chooseFile_btn.setText(QCoreApplication.translate("MainWindow", u"Choose File", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Audio File Path:", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">PiFmRds GUI</span></p></body></html>", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"FM Freq:", None))
        self.setFreq_btn.setText(QCoreApplication.translate("MainWindow", u"Set Freq", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Audio File:", None))
        self.textBrowser.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'SimSun'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'PibotoLt'; font-size:12pt; font-weight:600;\">Info</span></p></body></html>", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"FM Freq:", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Ps Text:", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Rt Text:", None))
        self.filePath.setText("")
        self.fmFreq.setText("")
        self.psText.setText("")
        self.rtText.setText("")
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Ps Text:", None))
        self.setPsText_btn.setText(QCoreApplication.translate("MainWindow", u"Set Ps Text", None))
        self.setRtText_btn.setText(QCoreApplication.translate("MainWindow", u"Set Rt Text", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Rt Text:", None))
        self.start_btn.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.version.setText(QCoreApplication.translate("MainWindow", u"v0.0.1 Alpha", None))
    # retranslateUi

